name: ${project.name}
version: ${project.version}
description: The ${project.name} plugin allows you to track chunk generation and versioning.
main: ${main.class}
author: hapm
database: true
load: STARTUP